name: Sync webhookd
on:
  pull_request:
  push:
  schedule:
    - cron: '06 2 * * *'

  run:
    name: Sync webhookd to Gitee
    runs-on: ubuntu-latest
    steps:
    # 同步个人仓库
    - name: Sync webhookd
    uses: Yikun/hub-mirror-action@master
    with:
      src: github/ncarlier
      dst: gitee/synchub
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
      dst_token: ${{ secrets.GITEE_TOKEN }}
      account_type: user
      static_list: "webhookd"
      clone_style: "ssh"
      force_update: true
      debug: true

