name: "Hub Mirror Action."
description: "在不同的 git 版本控制系统中同步代码。 (github/gitee)."
author: "Jonny.Chang"
branding:
  icon: "upload-cloud"
  color: "gray-dark"
inputs:
  dst_key:
    description: "专用 SSH 密钥，用于在系统之间推送代码。"
    required: true
  dst_token:
    description: "Token 用于在系统中创建仓库。"
    required: true
  dst:
    description: "目标组织名称。"
    required: true
  src:
    description: "源组织名称。"
    required: true
  account_type:
    description: "同步账户类型：org, user。默认 user。"
    default: 'user'
  clone_style:
    description: "克隆模式 https 或 ssh；默认 https。"
    default: 'https'
  cache_path:
    description: "缓存路径，默认： /github/workspace/hub-mirror-cache 。"
    default: '/github/workspace/hub-mirror-cache'
  black_list:
    description: "高优先级，仓库黑名单列表，如：'repo1,repo2,repo3'"
    default: ''
  white_list:
    description: "低优先级, 仓库白名单列表，如：'repo1,repo2,repo3'"
    default: ''
  static_list:
    description: "单仓库列表，不要从黑白名单中导入，如：'repo1,repo2,repo3'"
    default: ''
  force_update:
    description: "强制更新仓库，在'git push'使用'-f'参数"
    default: false
  debug:
    description: "开启 debug 可以显示详细日志。"
    default: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.dst_key }}
    - ${{ inputs.dst_token }}
    - ${{ inputs.src }}
    - ${{ inputs.dst }}
    - ${{ inputs.account_type }}
    - ${{ inputs.clone_style }}
    - ${{ inputs.cache_path }}
    - ${{ inputs.black_list }}
    - ${{ inputs.white_list }}
    - ${{ inputs.static_list }}
    - ${{ inputs.force_update}}
    - ${{ inputs.debug}}
