name: Sync personal repos
on:
  pull_request:
  push:
  schedule:
    - cron: '00 2 * * *'
jobs:
  run:
    name: Sync personal repos to gitee
    runs-on: ubuntu-latest
    steps:
    
    - name: authorise ssh host
      run: sudo mkdir /root/.ssh/ \
        && sudo chmod 700 /root/.ssh \
        && sudo ssh-keyscan github.com > /root/.ssh/known_hosts

    - name: add key and set permission
      run: sudo echo "${{ secrets.GITEE_PRIVATE_KEY }}" >> /root/.ssh/id_rsa \
        && sudo echo "${{ secrets.GITEE_PUBLIC_KEY }}" > /root/.ssh/id_rsa.pub \
        && sudo chmod 600 /root/.ssh/id_rsa.pub \
        && sudo chmod 600 /root/.ssh/id_rsa
        
    - name: Sync persional repos
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/hellenhub
        dst: gitee/jonnyhub
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: user
        static_list: "jonnyhub"
        clone_style: "ssh"
        force_update: true
        debug: true

