name: Gitee org repos mirror jobs
on:
  pull_request:
  push:
  schedule:
    - cron: '02 2 * * *'
jobs:
  run:
    name: Sync org repos to gitee
    runs-on: ubuntu-latest
    steps:
    - name: Sync org repos
    uses: Yikun/hub-mirror-action@master
    with:
      src: github/eoysky
      dst: gitee/eoysky
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
      dst_token: ${{ secrets.GITEE_TOKEN }}
      account_type: org
      #static_list: ""
      clone_style: "ssh"
      force_update: true
      debug: true

