name: Sync personal repos
on:
  pull_request:
  push:
  schedule:
    - cron: '00 2 * * *'
jobs:
  run:
    name: Sync personal repos to gitee
    runs-on: ubuntu-latest
    steps:
    - run: whoami 
    - run: sudo mkdir -p /root/.ssh
    - run: sudo ls -la /root/.ssh/
    - run: sudo echo  ${ secrets.GITEE_PRIVATE_KEY }
    - run: sudo echo ${{ secrets.GITEE_PUBLIC_KEY }}
    - run: sudo chmod 700 /root/.ssh 
    - run: sudo touch /root/.ssh/known_hosts 
    - run: sudo echo "${{ secrets.GITEE_PRIVATE_KEY }}" >> /root/.ssh/id_rsa
    - run: sudo echo "${{ secrets.GITEE_PUBLIC_KEY }}" > /root/.ssh/id_rsa.pub
    - run: sudo chmod 600 /root/.ssh/id_rsa.pub 
    - run: sudo chmod 600 /root/.ssh/id_rsa
        
    - name: Sync persional repos
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/hellenhub
        dst: gitee/jonnyhub
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        account_type: user
        static_list: "jonnyhub"
        clone_style: "ssh"
        force_update: true
        debug: true

